fix(snap): make secretstore connect hook idempotent (#3815)
Fixes https://github.com/edgexfoundry/edgex-go/issues/3814

Signed-off-by: Farshid Tavakolizadeh <farshid.tavakolizadeh@canonical.com>

diff --git a/snap/hooks/prepare-plug-edgex-secretstore-token b/snap/hooks/prepare-plug-edgex-secretstore-token
--- a/snap/hooks/prepare-plug-edgex-secretstore-token
+++ b/snap/hooks/prepare-plug-edgex-secretstore-token
@@ -29,7 +29,7 @@
 # able to share the same token.
 
 SLOTDIRS=$(snapctl get :edgex-secretstore-token --slot source.write)
-logger "edgex-secretstore-token: prepare SLOTDIRS=$SLOTDIRS"
+logger "edgex-secretstore-token: prepare SLOTDIRS=$(echo $SLOTDIRS)"
 DIRS=$(jq -r '.[]'  <<< "$SLOTDIRS" ) 
 
 for tokenpath in $DIRS;
@@ -39,10 +39,10 @@ do
     APP_SVC_TOKEN="$SNAP_DATA/secrets/${filename}/secrets-token.json"
     TARGET_PATH="/tmp/${filename}-secrets-token.json"
     if [ -f "$APP_SVC_TOKEN" ]; then
-        logger "edgex-secretstore-token: token found in $APP_SVC_TOKEN; moving to $TARGET_PATH"
-        mv "$APP_SVC_TOKEN" "$TARGET_PATH"
+        logger "edgex-secretstore-token: copying $APP_SVC_TOKEN to $TARGET_PATH"
+        cp "$APP_SVC_TOKEN" "$TARGET_PATH"
+    else
+        logger --stderr "edgex-secretstore-token: could not find token for $filename"
+        exit 1
     fi
 done
-
-
-
